;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<AppWindow>>>;;;
[AppWindow]
DpiWindowSizeFactor=1
WindowPosition=0,23
WindowSize=1920,1009
;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Conversations]
Pos=0,673
Size=476,307
Collapsed=0

[Window][Graph View]
Pos=480,50
Size=1432,935
Collapsed=0

[Window][File Loader]
Pos=0,50
Size=476,307
Collapsed=0

[Window][Detail]
Pos=0,361
Size=476,307
Collapsed=0

[Window][About PCC Dialog Viewer]
Pos=770,399
Size=380,210
Collapsed=0

[Window][##content]
Pos=0,20
Size=1920,965
Collapsed=0

[Docking][Data]

;;;<<<Layout_655921752_Default>>>;;;
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
